-- ================================================================
-- SMART BELT AI HEALTHCARE INTELLIGENCE SYSTEM - DATABASE SCHEMA
-- ================================================================
-- This schema is COMPLETELY INDEPENDENT from the Saline system
-- No patient data is shared between modules
-- ================================================================

-- ================================================================
-- 1. PATIENT PROFILES (Smart Belt Module Only)
-- ================================================================

create table smart_belt_patients (
  id bigint generated by default as identity primary key,
  
  -- Basic Information
  name text not null,
  age int not null check (age > 0 and age < 150),
  gender text check (gender in ('Male', 'Female', 'Other')),
  
  -- Medical Background
  medical_history jsonb default '[]'::jsonb, -- [{condition: "Diabetes", diagnosed: "2020-01-15"}]
  allergies jsonb default '[]'::jsonb, -- ["Penicillin", "Aspirin"]
  
  -- Critical Health History
  stroke_history boolean default false,
  heart_disease_history boolean default false,
  seizure_history boolean default false,
  diabetes boolean default false,
  hypertension boolean default false,
  
  -- Current Medications
  medications jsonb default '[]'::jsonb, -- [{name: "Metformin", dosage: "500mg", frequency: "2x daily"}]
  
  -- Baseline Health Values (for anomaly detection)
  baseline_hr int check (baseline_hr > 0 and baseline_hr < 200), -- Normal resting heart rate
  baseline_spo2 int check (baseline_spo2 >= 0 and baseline_spo2 <= 100), -- Normal oxygen level
  baseline_temp float check (baseline_temp > 90 and baseline_temp < 110), -- Normal body temperature (°F)
  
  -- Device Linkage
  device_id text unique, -- Currently linked Smart Belt device ID
  
  -- Emergency Contacts
  emergency_contact_name text,
  emergency_contact_phone text,
  
  -- Status & Metadata
  admitted_at timestamp with time zone default now(),
  discharged_at timestamp with time zone,
  status text check (status in ('active', 'discharged')) default 'active',
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Index for active patient queries
create index idx_smart_belt_patients_status on smart_belt_patients(status) where status = 'active';
create index idx_smart_belt_patients_device on smart_belt_patients(device_id) where device_id is not null;

-- ================================================================
-- 2. TIME-SERIES SENSOR DATA (Auto-deleted after 24 hours)
-- ================================================================

create table smart_belt_sensor_data (
  id bigint generated by default as identity primary key,
  patient_id bigint references smart_belt_patients(id) on delete cascade,
  device_id text not null,
  
  -- Vital Signs
  ecg_value float,
  heart_rate int check (heart_rate >= 0 and heart_rate <= 300),
  spo2 int check (spo2 >= 0 and spo2 <= 100),
  temperature float check (temperature > 90 and temperature < 110), -- °F
  
  -- Motion Data
  accel_x float,
  accel_y float,
  accel_z float,
  motion_activity_index float, -- Calculated motion intensity
  
  -- Status Flags
  wearing_status boolean default true,
  leads_ok boolean default true, -- ECG leads properly connected
  
  -- Real-time AI Analysis Results
  anomaly_detected boolean default false,
  anomaly_type text, -- 'ecg_irregular', 'hr_spike', 'hr_drop', 'spo2_drop', 'temp_spike', 'fall_detected', 'seizure_motion'
  risk_score int check (risk_score >= 0 and risk_score <= 100),
  
  timestamp timestamp with time zone default now()
);

-- Indexes for time-series queries
create index idx_sensor_data_patient_time on smart_belt_sensor_data(patient_id, timestamp desc);
create index idx_sensor_data_timestamp on smart_belt_sensor_data(timestamp);
create index idx_sensor_data_anomalies on smart_belt_sensor_data(patient_id, timestamp desc) where anomaly_detected = true;

-- ================================================================
-- 3. DAILY AI REPORTS (Permanent - replaces raw data)
-- ================================================================

create table smart_belt_daily_reports (
  id bigint generated by default as identity primary key,
  patient_id bigint references smart_belt_patients(id) on delete cascade,
  report_date date not null,
  
  -- Summary Metrics
  avg_heart_rate float,
  max_heart_rate int,
  min_heart_rate int,
  avg_spo2 float,
  min_spo2 int,
  avg_temperature float,
  max_temperature float,
  activity_level text check (activity_level in ('rest', 'low', 'moderate', 'active', 'volatile')),
  
  -- AI Insights
  stability_score int check (stability_score >= 0 and stability_score <= 100),
  anomaly_count int default 0,
  critical_incidents jsonb default '[]'::jsonb, -- [{timestamp, type, severity, vitals_snapshot}]
  
  -- Risk Trends
  stroke_risk_trend text check (stroke_risk_trend in ('increasing', 'stable', 'decreasing', 'volatile')),
  seizure_risk_trend text check (seizure_risk_trend in ('increasing', 'stable', 'decreasing', 'volatile')),
  cardiac_risk_trend text check (cardiac_risk_trend in ('increasing', 'stable', 'decreasing', 'volatile')),
  
  -- Daily Risk Averages
  avg_stroke_risk float,
  avg_seizure_risk float,
  avg_cardiac_risk float,
  
  -- AI Summary (Natural Language)
  ai_summary text, -- "Patient showed stable vitals throughout the day. 3 minor HR spikes observed during afternoon hours..."
  recommendations text, -- "Continue monitoring. Consider adjusting medication schedule."
  
  created_at timestamp with time zone default now(),
  
  -- Ensure one report per patient per day
  unique(patient_id, report_date)
);

-- Index for report retrieval
create index idx_daily_reports_patient_date on smart_belt_daily_reports(patient_id, report_date desc);

-- ================================================================
-- 4. REAL-TIME PREDICTIONS (Updated continuously)
-- ================================================================

create table smart_belt_predictions (
  patient_id bigint primary key references smart_belt_patients(id) on delete cascade,
  
  -- Stroke Risk Predictions
  stroke_risk_now int check (stroke_risk_now >= 0 and stroke_risk_now <= 100) default 0,
  stroke_risk_24h int check (stroke_risk_24h >= 0 and stroke_risk_24h <= 100) default 0,
  stroke_risk_48h int check (stroke_risk_48h >= 0 and stroke_risk_48h <= 100) default 0,
  stroke_severity text check (stroke_severity in ('low', 'medium', 'high', 'critical')) default 'low',
  
  -- Seizure Risk Predictions
  seizure_risk_now int check (seizure_risk_now >= 0 and seizure_risk_now <= 100) default 0,
  seizure_risk_24h int check (seizure_risk_24h >= 0 and seizure_risk_24h <= 100) default 0,
  seizure_risk_48h int check (seizure_risk_48h >= 0 and seizure_risk_48h <= 100) default 0,
  seizure_severity text check (seizure_severity in ('low', 'medium', 'high', 'critical')) default 'low',
  
  -- Cardiac Risk Predictions
  cardiac_risk_now int check (cardiac_risk_now >= 0 and cardiac_risk_now <= 100) default 0,
  cardiac_risk_24h int check (cardiac_risk_24h >= 0 and cardiac_risk_24h <= 100) default 0,
  cardiac_risk_48h int check (cardiac_risk_48h >= 0 and cardiac_risk_48h <= 100) default 0,
  cardiac_severity text check (cardiac_severity in ('low', 'medium', 'high', 'critical')) default 'low',
  
  -- Oxygen Crash Risk
  oxygen_crash_risk int check (oxygen_crash_risk >= 0 and oxygen_crash_risk <= 100) default 0,
  
  -- Risk Factors (what's contributing to the risk)
  risk_factors jsonb default '[]'::jsonb, -- ["Rising Baseline HR (+15% over 6h)", "ECG irregularities (3 events)", "Low HRV indicating stress"]
  
  -- Prediction Confidence
  prediction_confidence float check (prediction_confidence >= 0 and prediction_confidence <= 1) default 0.5,
  
  last_updated timestamp with time zone default now()
);

-- ================================================================
-- 5. EMERGENCY ALERTS (Permanent History)
-- ================================================================

create table smart_belt_emergency_alerts (
  id bigint generated by default as identity primary key,
  patient_id bigint references smart_belt_patients(id) on delete cascade,
  
  -- Alert Information
  alert_type text not null check (alert_type in (
    'STROKE_WARNING',
    'STROKE_CRITICAL',
    'SEIZURE_DETECTED',
    'CARDIAC_ARRHYTHMIA',
    'CARDIAC_CRITICAL',
    'FALL_DETECTED',
    'OXYGEN_CRITICAL',
    'TEMPERATURE_CRITICAL'
  )),
  severity text check (severity in ('warning', 'high', 'critical')) not null,
  
  -- Snapshot of vitals at alert time
  vitals_snapshot jsonb not null, -- {hr: 145, spo2: 85, temp: 102.4, ecg: 1234, motion: [x,y,z]}
  
  -- Risk scores at time of alert
  risk_scores jsonb, -- {stroke: 85, seizure: 20, cardiac: 75}
  
  -- Alert message
  message text, -- "Critical oxygen desaturation detected. SpO2 dropped to 85% and sustained for 2 minutes."
  
  -- Alert Status
  acknowledged boolean default false,
  acknowledged_by text,
  acknowledged_at timestamp with time zone,
  
  -- Resolution
  resolved boolean default false,
  resolved_by text,
  resolved_at timestamp with time zone,
  resolution_notes text,
  
  created_at timestamp with time zone default now()
);

-- Indexes for alert queries
create index idx_alerts_patient_time on smart_belt_emergency_alerts(patient_id, created_at desc);
create index idx_alerts_unacknowledged on smart_belt_emergency_alerts(created_at desc) where acknowledged = false;
create index idx_alerts_severity on smart_belt_emergency_alerts(severity, created_at desc);

-- ================================================================
-- 6. ANALYSIS METADATA (Track AI processing status)
-- ================================================================

create table smart_belt_analysis_metadata (
  patient_id bigint primary key references smart_belt_patients(id) on delete cascade,
  
  -- Last Analysis Timestamps
  last_realtime_analysis timestamp with time zone,
  last_prediction_update timestamp with time zone,
  last_daily_report timestamp with time zone,
  
  -- Data Statistics
  total_data_points_today int default 0,
  total_anomalies_today int default 0,
  total_alerts_today int default 0,
  
  -- Processing Flags
  analysis_enabled boolean default true,
  alerts_enabled boolean default true,
  
  updated_at timestamp with time zone default now()
);

-- ================================================================
-- 7. ENABLE REAL-TIME SUBSCRIPTIONS
-- ================================================================

-- Enable Supabase Realtime for live updates
alter publication supabase_realtime add table smart_belt_patients;
alter publication supabase_realtime add table smart_belt_sensor_data;
alter publication supabase_realtime add table smart_belt_predictions;
alter publication supabase_realtime add table smart_belt_emergency_alerts;

-- ================================================================
-- 8. ROW LEVEL SECURITY POLICIES (Example - adjust for production)
-- ================================================================

-- For now, allow all operations (in production, add proper authentication)
create policy "Enable read access for all users" on smart_belt_patients for select using (true);
create policy "Enable insert for all users" on smart_belt_patients for insert with check (true);
create policy "Enable update for all users" on smart_belt_patients for update using (true);

create policy "Enable read access for all users" on smart_belt_sensor_data for select using (true);
create policy "Enable insert for devices" on smart_belt_sensor_data for insert with check (true);

create policy "Enable read access for all users" on smart_belt_predictions for select using (true);
create policy "Enable update for analysis engine" on smart_belt_predictions for update using (true);

create policy "Enable read access for all users" on smart_belt_emergency_alerts for select using (true);
create policy "Enable insert for alert system" on smart_belt_emergency_alerts for insert with check (true);
create policy "Enable update for acknowledgement" on smart_belt_emergency_alerts for update using (true);

create policy "Enable read access for all users" on smart_belt_daily_reports for select using (true);
create policy "Enable insert for report generator" on smart_belt_daily_reports for insert with check (true);

-- ================================================================
-- 9. FUNCTIONS & TRIGGERS
-- ================================================================

-- Auto-update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_smart_belt_patients_updated_at
  before update on smart_belt_patients
  for each row execute function update_updated_at_column();

-- ================================================================
-- 10. DAILY DATA CLEANUP FUNCTION
-- ================================================================

-- Function to delete sensor data older than 24 hours
create or replace function cleanup_old_sensor_data()
returns void as $$
begin
  delete from smart_belt_sensor_data
  where timestamp < now() - interval '24 hours';
  
  raise notice 'Deleted sensor data older than 24 hours';
end;
$$ language plpgsql;

-- Schedule this function to run daily at midnight (use pg_cron or external scheduler)

-- ================================================================
-- MIGRATION NOTES
-- ================================================================
-- To apply this schema:
-- 1. Run this SQL in your Supabase SQL Editor
-- 2. Ensure Realtime is enabled for the tables
-- 3. Set up pg_cron or external cron job to run cleanup_old_sensor_data() daily
-- ================================================================
