-- SMART BELT SUPABASE SCHEMA

-- 1. LIVE TELEMETRY TABLE (Overwritten/Patched by Device)
-- This table replaces the Firebase Realtime Database node.
create table smart_belt_live (
  device_id text primary key,
  bpm int,
  spo2 int,
  temp float,
  ir_val int,
  ecg_val int,
  leads_ok boolean,
  wearing_status boolean default false,
  acc_x float,
  acc_y float,
  acc_z float,
  gyro_x float,
  last_updated timestamp with time zone default now()
);

-- 2. ALERTS/INCIDENTS TABLE (History)
-- Used by the Dashboard Timeline and AI History
create table smart_belt_alerts (
  id bigint generated by default as identity primary key,
  device_id text references smart_belt_live(device_id),
  risk_type text, -- 'cardiac', 'seizure', 'fall'
  severity text, -- 'warning', 'critical'
  details jsonb, -- Snapshot of vitals at time of alert
  created_at timestamp with time zone default now()
);

-- 3. ENABLE REALTIME
-- This allows the Dashboard to stream changes instantly
alter publication supabase_realtime add table smart_belt_live;
alter publication supabase_realtime add table smart_belt_alerts;

-- 4. POLICIES (Example: Open read for dashboard)
create policy "Public Read" on smart_belt_live for select using (true);
create policy "Device Update" on smart_belt_live for update using (true); -- In prod, secure this!
create policy "Device Insert" on smart_belt_live for insert with check (true);
